# Generated by Django 5.1.1 on 2025-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE')], default='BRONZE', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
