# Generated by Django 5.1.1 on 2025-03-31 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_booking_app', '0002_customuser_membership_type_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
