---
- name: Deploy Fitness Booking Application
  hosts: host_server
  become: yes
  vars:
    app_dir: "/home/{{ ansible_user }}/fitnessclasses_booking_app-mulibrian"
    nginx_port: 8087
    mailhog_port: 8027
  roles:
    - fb
