services:
  django:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.django
    container_name: django
    restart: always
    depends_on:
      - postgres
      - mailhog
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - app_network
  postgres:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.postgresql
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - app_network

  mailhog:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.mailhog
    container_name: mailhog
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.nginx
    container_name: nginx
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network


networks: 
  app_network:
    driver: bridge
volumes:
  postgres_data:
