FROM nginx:latest
#Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf
#Copy a configuration file from the current directory
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

#expose http and https ports
EXPOSE 80 443
