FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration to the correct directory
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Run Nginx normally (no need to specify a custom config file)
CMD ["nginx", "-g", "daemon off;"]
