name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install -r fitness_classes_booking/requirements.txt
      - name: Run tests
        run: |
            python fitness_classes_booking/manage.py test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: |
          docker compose -f fitness_classes_booking/docker-compose.yaml up -d --build

      - name: Wait for database to be ready
        run: |
          until docker compose -f fitness_classes_booking/docker-compose.yaml exec -T postgres pg_isready -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
          done


      - name: Run database migrations
        run: |
          docker compose -f ./docker-compose.yaml exec -T django python /code/manage.py migrate

      - name: Run tests
        run: |
          docker compose -f ./docker-compose.yaml exec -T django python /code/manage.py test

      - name: Stop and remove containers
        if: always()
        run: |
          docker compose -f fitness_classes_booking/docker-compose.yaml down